=== evgeniyyaskevich/xmlwebparsing/src/main/resource/medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://www.epam.by/javaweb/evgeniyyaskecih/xmlwebparsing/medicines"
        xmlns:tns="https://www.epam.by/javaweb/evgeniyyaskecih/xmlwebparsing/medicines"
        elementFormDefault="qualified">

    <element name="medicines">
        <complexType>
            <sequence>
                <element name="medicine"
                         type="tns:Medicine"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Medicine">
        <sequence>
            <element name="name" type="string"/>
            <element name="producer" type="string"/>
            <element name="group" type="tns:Group"/>
            <element name="analogs" type="tns:Analogs"/>
            <element name="versions" type="tns:Versions"/>
        </sequence>
    </complexType>

    <simpleType name="Group">
        <restriction base="string">
            <enumeration value="Pain Reliever"/>
            <enumeration value="Antibiotic"/>
            <enumeration value="Antiseptic"/>
            <enumeration value="Laxative"/>
            <enumeration value="Sedative"/>
            <enumeration value="Tranquilizer"/>
            <enumeration value="Vitamins"/>
            <enumeration value="Antiviral"/>
            <enumeration value="Antifebrile"/>
        </restriction>
    </simpleType>

    <complexType name="Analogs">
        <sequence>
            <element name="analog" type="tns:Analog" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Analog">
        <simpleContent>
            <extension base="string">
                <attribute name="origin">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="foreign"/>
                            <enumeration value="local"/>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </simpleContent>
    </complexType>

    <complexType name="Versions">
        <sequence>
            <element name="version" maxOccurs="unbounded">
                <complexType>
                    <sequence>
                        <element name="certificate" type="tns:Certificate"/>
                        <element name="package" type="tns:Package"/>
                        <element name="dosage" type="tns:Dosage"/>
                    </sequence>
                    <attribute name="consistency" type="tns:Consistency" use="required"/>
                </complexType>
            </element>
        </sequence>
    </complexType>

    <simpleType name="Consistency">
        <restriction base="string">
            <enumeration value="pill"/>
            <enumeration value="syrup"/>
            <enumeration value="drops"/>
            <enumeration value="ointment"/>
            <enumeration value="capsule"/>
        </restriction>
    </simpleType>

    <complexType name="Certificate">
        <sequence>
            <element name="issueDate" type="date"/>
            <element name="expirationDate" type="date"/>
            <element name="registeringOrganization" type="string"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>

    <complexType name="Package">
        <sequence>
            <element name="amount" type="positiveInteger"/>
            <element name="price" type="tns:Price"/>
        </sequence>
        <attribute name="type" default="box"/>
    </complexType>

    <simpleType name="Price">
        <restriction base="decimal">
            <minExclusive value="0"/>
            <maxInclusive value="1000"/>
        </restriction>
    </simpleType>

    <complexType name="Dosage">
        <sequence>
            <element name="dose" type="tns:Dose"/>
            <element name="periodicity" type="tns:Periodicity"/>
        </sequence>
    </complexType>

    <simpleType name="Periodicity">
        <restriction base="string">
            <pattern value="\s*[1-9][0-9]*[\-]?\s*[0-9]*\s+(months?|weeks?|days?|hours?)\s*"/>
            <whiteSpace value="replace"/>
        </restriction>
    </simpleType>

    <simpleType name="Dose">
        <restriction base="string">
            <pattern value="\s*[1-9][0-9]*[\-]?\s*[0-9]*\s+(mg|ml|pieces|drops)\s*"/>
        </restriction>
    </simpleType>

</schema>

=== evgeniyyaskevich/xmlwebparsing/src/main/resource/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>

<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="https://www.epam.by/javaweb/evgeniyyaskecih/xmlwebparsing/medicines"
           xsi:schemaLocation="https://www.epam.by/javaweb/evgeniyyaskecih/xmlwebparsing/medicines medicines.xsd">
    <medicine>
        <name>Aspirin</name>
        <producer>Bayer Company</producer>
        <group>Pain Reliever</group>
        <analogs>
            <analog origin="foreign">Epicor</analog>
            <analog origin="local">Aspicard</analog>
            <analog>Kardiomagnyl</analog>
        </analogs>
        <versions>
            <version consistency="pill">
                <certificate id="ID-28012019228">
                    <issueDate>2019-01-28</issueDate>
                    <expirationDate>2020-12-31</expirationDate>
                    <registeringOrganization>Official Bayer Protection Company</registeringOrganization>
                </certificate>
                <package>
                    <amount>20</amount>
                    <price>25.3</price>
                </package>
                <dosage>
                    <dose>81 mg</dose>
                    <periodicity>3-5 days</periodicity>
                </dosage>
            </version>
        </versions>
    </medicine>

    <medicine>
        <name>Corvalolum</name>
        <producer>LekPharm</producer>
        <group>Sedative</group>
        <analogs>
            <analog origin="local">Corvaldin</analog>
            <analog origin="local">Barboval</analog>
        </analogs>
        <versions>
            <version consistency="drops">
                <certificate id="ID-28012019230">
                    <issueDate>2013-11-13</issueDate>
                    <expirationDate>2020-12-31</expirationDate>
                    <registeringOrganization>Ukrainian Pharmacy Administration</registeringOrganization>
                </certificate>
                <package type="bottle">
                    <amount>50</amount>
                    <price>3.35</price>
                </package>
                <dosage>
                    <dose>7-10 drops</dose>
                    <periodicity>1 day</periodicity>
                </dosage>
            </version>
        </versions>
    </medicine>

    <medicine>
        <name>Groprinosin</name>
        <producer>Gedeon Richter</producer>
        <group>Antiviral</group>
        <analogs>
            <analog origin="local">Anapheron</analog>
            <analog origin="foreign">Arbidol</analog>
        </analogs>
        <versions>
            <version consistency="pill">
                <certificate id="ID-28012019299">
                    <issueDate>2000-01-13</issueDate>
                    <expirationDate>2020-12-21</expirationDate>
                    <registeringOrganization>Sun Pharmaceutical Industries</registeringOrganization>
                </certificate>
                <package>
                    <amount>50</amount>
                    <price>13</price>
                </package>
                <dosage>
                    <dose>500 mg</dose>
                    <periodicity>5-7 days</periodicity>
                </dosage>
            </version>

            <version consistency="syrup">
                <certificate id="ID-28012019222">
                    <issueDate>2014-05-13</issueDate>
                    <expirationDate>2020-12-21</expirationDate>
                    <registeringOrganization>Sun Pharmaceutical Industries</registeringOrganization>
                </certificate>
                <package type="bottle">
                    <amount>250</amount>
                    <price>10</price>
                </package>
                <dosage>
                    <dose>10 ml</dose>
                    <periodicity>5-7 days</periodicity>
                </dosage>
            </version>
        </versions>
    </medicine>

    <medicine>
        <name>NormoBakt</name>
        <producer>Medana Pharma</producer>
        <group>Antibiotic</group>
        <analogs>
            <analog>NormoBakt Junior</analog>
        </analogs>
        <versions>
            <version consistency="powder">
                <certificate id="ID-28012019234">
                    <issueDate>2012-03-23</issueDate>
                    <expirationDate>2020-02-15</expirationDate>
                    <registeringOrganization>General Government Pharmacy</registeringOrganization>
                </certificate>
                <package>
                    <amount>30</amount>
                    <price>9</price>
                </package>
                <dosage>
                    <dose>3 g</dose>
                    <periodicity>1 day</periodicity>
                </dosage>
            </version>

            <version consistency="tablet">
                <certificate id="ID-28012019235">
                    <issueDate>2000-11-22</issueDate>
                    <expirationDate>2025-07-08</expirationDate>
                    <registeringOrganization>Russian General Tablet Production</registeringOrganization>
                </certificate>
                <package>
                    <amount>20</amount>
                    <price>5</price>
                </package>
                <dosage>
                    <dose>500 mg</dose>
                    <periodicity>2 days</periodicity>
                </dosage>
            </version>
        </versions>
    </medicine>

    <medicine>
        <name>Loperamida</name>
        <producer>Borisov BelPharm</producer>
        <group>Laxative</group>
        <analogs>
            <analog origin="foreign">Loperamidus</analog>
            <analog origin="local">GidroChloridus</analog>
            <analog>Loperamid Premium</analog>
        </analogs>
        <versions>
            <version consistency="capsule">
                <certificate id="ID-339943">
                    <issueDate>2019-10-02</issueDate>
                    <expirationDate>2020-07-06</expirationDate>
                    <registeringOrganization>BelMedMedicines</registeringOrganization>
                </certificate>
                <package>
                    <amount>10</amount>
                    <price>0.75</price>
                </package>
                <dosage>
                    <dose>2 mg</dose>
                    <periodicity>5 hours</periodicity>
                </dosage>
            </version>
        </versions>
    </medicine>

    <medicine>
        <name>Doctor Mom</name>
        <producer>Unic PharmaSutical</producer>
        <group>Antifebrile</group>
        <analogs>
            <analog origin="foreign">Amtersol</analog>
        </analogs>
        <versions>
            <version consistency="syrup">
                <certificate id="ID-9933994322">
                    <issueDate>2013-12-07</issueDate>
                    <expirationDate>2025-11-18</expirationDate>
                    <registeringOrganization>Minsk Pharmacy</registeringOrganization>
                </certificate>
                <package type="bottle">
                    <amount>300</amount>
                    <price>3</price>
                </package>
                <dosage>
                    <dose>15 ml</dose>
                    <periodicity>2 hours</periodicity>
                </dosage>
            </version>
        </versions>
    </medicine>

    <medicine>
        <name>Ambroxol</name>
        <producer>Borisov BelPharm</producer>
        <group>Antiviral</group>
        <analogs>
            <analog origin="foreign">Bronhorus</analog>
            <analog>Halicsol</analog>
        </analogs>
        <versions>
            <version consistency="syrup">
                <certificate id="ID-123454322">
                    <issueDate>2011-09-07</issueDate>
                    <expirationDate>2025-11-23</expirationDate>
                    <registeringOrganization>Minsk Pharmacy</registeringOrganization>
                </certificate>
                <package type="bottle">
                    <amount>315</amount>
                    <price>1.5</price>
                </package>
                <dosage>
                    <dose>30 mg</dose>
                    <periodicity>24 hours</periodicity>
                </dosage>
            </version>

            <version consistency="tablet">
                <certificate id="ID-943124213">
                    <issueDate>2015-10-07</issueDate>
                    <expirationDate>2020-03-23</expirationDate>
                    <registeringOrganization>Moscow General Pharmacy</registeringOrganization>
                </certificate>
                <package>
                    <amount>20</amount>
                    <price>5</price>
                </package>
                <dosage>
                    <dose>30 mg</dose>
                    <periodicity>2-3 hours</periodicity>
                </dosage>
            </version>
        </versions>
    </medicine>

    <medicine>
        <name>Karnitina Chlorid</name>
        <producer>BelMedPharmacy</producer>
        <group>Antiseptic</group>
        <analogs>
            <analog origin="foreign">Ceracson</analog>
        </analogs>
        <versions>
            <version consistency="powder">
                <certificate id="ID-28012019333">
                    <issueDate>2012-01-22</issueDate>
                    <expirationDate>2023-05-31</expirationDate>
                    <registeringOrganization>Minsk Official Pharmacy Agent</registeringOrganization>
                </certificate>
                <package>
                    <amount>10</amount>
                    <price>13.1</price>
                </package>
                <dosage>
                    <dose>2 g</dose>
                    <periodicity>3-5 days</periodicity>
                </dosage>
            </version>
        </versions>
    </medicine>


    <medicine>
        <name>ChlorGidrat</name>
        <producer>Gedeon Richter</producer>
